#include <ros/ros.h>
#include "last_letter_2_libs/math_lib.hpp"
#include <last_letter_2_msgs/get_model_states_srv.h>
#include <last_letter_2_msgs/get_control_signals_srv.h>
#include <last_letter_2_msgs/airdata_srv.h>
#include <last_letter_2_msgs/air_data.h>
#include <last_letter_2_msgs/control_signals.h>
#include <last_letter_2_msgs/model_states.h>
#include <last_letter_2_msgs/aero_wrenches.h>
#include <last_letter_2_msgs/prop_wrenches.h>
#include <last_letter_2_msgs/model_wrenches.h>
#include <last_letter_2_msgs/apply_wrench_srv.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3Stamped.h>
#include <tf2_ros/transform_listener.h>
#include <tf2_geometry_msgs/tf2_geometry_msgs.h>
#include <std_srvs/Empty.h>
#include <rosgraph_msgs/Clock.h>
#include <math.h>
#include <ctime>
#include <string>

class Aerodynamics;
class Propulsion;
class Dynamics;
class Model;
class Master;
class Factory;
class Polynomial;
