#airfoil Aerodynamic Parameters
#aerodynamicsType: 0:NoAerodynamics, 1:StdLinearAero 2:HCUAVAero
airfoil/nWings: 1

airfoil1/aileron: 1   #1 if airfoil1 affects roll, otherwise 0
airfoil1/elevator: 1  #1 if airfoil1 affects pitch, otherwise 0
airfoil1/rudder: 1    #1 if airfoil1 affects yaw, otherwise 0

airfoil1/chanGimbal: -1
airfoil1/gimbalAngle_max: 0.0

airfoil1/CGOffset: [-0.02, 0.00, -0.05] # vector from CG to CoL
airfoil1/mountOrientation: [0.0, 0.0, 0.0] # Euler rotations from body axes to propeller normal plane. Gimbal rotation axis should be in z-axis.
airfoil1/gimbalAxis: 0
airfoil1/aerodynamicsType: 1
airfoil1/s: 0.45   #wing surface = b*c
airfoil1/b: 1.88   #wingspan
airfoil1/c: 0.24   #wing mean cord

airfoil1/c_lift_0: 0.56
airfoil1/c_lift_deltae: 0.0
airfoil1/c_lift_a: 6.9
airfoil1/c_lift_q: 0
airfoil1/mcoeff: 50
airfoil1/oswald: 0.9
airfoil1/alpha_stall: 0.4712
airfoil1/c_drag_q: 0.0
airfoil1/c_drag_deltae: 0.0
airfoil1/c_drag_p: 0.0437
airfoil1/c_drag_0: 0.03
airfoil1/c_drag_a: 0.3
airfoil1/c_y_0: 0
airfoil1/c_y_b: -0.98
airfoil1/c_y_p: 0
airfoil1/c_y_r: 0
airfoil1/c_y_deltaa: 0
airfoil1/c_y_deltar: -0.2 #opposite sign than c_n_deltar

airfoil1/c_l_0: 0
airfoil1/c_l_p: -1.0
airfoil1/c_l_b: -0.12
airfoil1/c_l_r: 0.14
airfoil1/c_l_deltaa: 0.25
airfoil1/c_l_deltar: -0.037
airfoil1/c_m_0: 0.045
airfoil1/c_m_a: -0.7
airfoil1/c_m_q: -20
airfoil1/c_m_deltae: 1.0
airfoil1/c_n_0: 0
airfoil1/c_n_b: 0.25
airfoil1/c_n_p: 0.022
airfoil1/c_n_r: -1
airfoil1/c_n_deltaa: 0.00
airfoil1/c_n_deltar: 0.1 #opposite sign than c_y_deltar

airfoil1/deltax_max: 0.3491
airfoil1/deltay_max: 0.3491
airfoil1/deltaz_max: 0.3491

airfoil1/chanAileron: 0
airfoil1/chanElevator: 1
airfoil1/chanRudder: 3
airfoil1/chanThrottle: 2

# airfoil 2
airfoil2/aileron: 1   #1 if airfoil2 affects roll, otherwise 0
airfoil2/elevator: 1  #1 if airfoil2 affects pitch, otherwise 0
airfoil2/rudder: 1 
airfoil2/aerodynamicsType: 0

airfoil2/chanAileron: 0
airfoil2/chanElevator: 1
airfoil2/chanRudder: 3
airfoil2/chanThrottle: 2

airfoil2/deltax_max: 0.3491
airfoil2/deltay_max: 0.3491
airfoil2/deltaz_max: 0.3491

# airfoil 3
airfoil3/aileron: 1   #1 if airfoil3 affects roll, otherwise 0
airfoil3/elevator: 1  #1 if airfoil3 affects pitch, otherwise 0
airfoil3/rudder: 1 
airfoil3/aerodynamicsType: 2

airfoil3/chanAileron: 0
airfoil3/chanElevator: 1
airfoil3/chanRudder: 3
airfoil3/chanThrottle: 2

airfoil3/deltax_max: 0.3491
airfoil3/deltay_max: 0.3491
airfoil3/deltaz_max: 0.3491