#service for applying the wrenches on each motor and airfoil

geometry_msgs/Vector3[3] airfoil_forces
geometry_msgs/Vector3[3] airfoil_torques
float32[4] motor_thrust
float32[4] motor_torque
---
std_msgs/Bool success