# HID configuration parameters
# All arrays must be 11 elements long
# Aileron, Elevator, Throttle and Rudder commands correspond to the positions 0, 1, 2 and 3 respectively.

# Logitech Extreme 3D Pro joystick
# Channel     [0      1     2     3     4     5     6     7     8     9    10  ]
/HID/axes:    [0,     1,    3,    2,   -1,   -1,    5,   -1,   -1,   -1,   -1  ]
/HID/buttons: [-1,   -1,   -1,   -1,   -1,    0,   -1,   -1,   -1,    6,   -1  ]
/HID/throws:  [-1.0, -1.0,  1.0, -1.0,  1.0,  1.0,  1.0,  0.0,  0.0,  1.0,  0.0]

# Mixer id number, see joy2chan.cpp code:
# 0 for no mixing
# 1 for airplane mixing
# 2 for quadrotor mixing
/HID/mixerid: 1